word_lists = {
    "fruits": [
        "apple", "apricot", "avocado", "banana", "blackberry", "blueberry", "boysenberry", "breadfruit",
        "cantaloupe", "carambola", "cherimoya", "cherry", "cloudberry", "coconut", "cranberry", "date",
        "dragonfruit", "durian", "elderberry", "feijoa", "fig", "goji berry", "gooseberry", "grape",
        "grapefruit", "guava", "honeydew", "huckleberry", "jabuticaba", "jackfruit", "jambul", "jujube",
        "kiwi", "kumquat", "lemon", "lime", "longan", "loquat", "lychee", "mango", "mangosteen",
        "marionberry", "melon", "mulberry", "nectarine", "orange", "papaya", "passion fruit", "peach",
        "pear", "persimmon", "pineapple", "pitaya", "plantain", "plum", "pomegranate", "pomelo",
        "prickly pear", "quince", "raspberry", "red currant", "rambutan", "sapodilla", "sapote",
        "soursop", "star apple", "star fruit", "strawberry", "tamarillo", "tamarind", "tangerine",
        "ugli fruit", "watermelon", "white currant", "white sapote", "xigua", "yellow watermelon",
        "yuzu", "zucchini", "kaki",
    ],

    "animals": [
        "aardvark", "albatross", "alligator", "alpaca", "ant", "anteater", "antelope", "ape", "armadillo",
        "baboon", "badger", "barracuda", "bat", "bear", "beaver", "bee", "bison", "boar", "buffalo",
        "butterfly", "camel", "capybara", "caribou", "cassowary", "cat", "caterpillar", "cattle", "chamois",
        "cheetah", "chicken", "chimpanzee", "chinchilla", "clam", "cobra", "cockroach", "cod", "cormorant",
        "coyote", "crab", "crane", "crocodile", "crow", "curlew", "deer", "dinosaur", "dog", "dogfish",
        "dolphin", "donkey", "dove", "dragonfly", "duck", "dugong", "eagle", "echidna", "eel", "eland",
        "elephant", "elephant seal", "elk", "emu", "falcon", "ferret", "finch", "fish", "flamingo", "fly",
        "fox", "frog", "gaur", "gazelle", "gerbil", "giant panda", "giraffe", "gnat", "gnu", "goat",
        "goose", "goldfish", "gorilla", "goshawk", "grasshopper", "grouse", "guanaco", "gull", "hamster",
        "hare", "hawk", "hedgehog", "heron", "herring", "hippopotamus", "hornet", "horse", "human",
        "hummingbird", "hyena", "ibex", "ibis", "jackal", "jaguar", "jellyfish", "kangaroo", "kingfisher",
        "koala", "komodo dragon", "kookaburra", "kouprey", "kudu", "lapwing", "lark", "lemur", "leopard",
        "lion", "llama", "lobster", "locust", "loris", "louse", "lyrebird", "magpie", "mallard", "manatee",
        "mandrill", "mantis", "marten", "meerkat", "mink", "mole", "mongoose", "monkey", "moose", "mosquito",
        "mouse", "mule", "narwhal", "newt", "nightingale", "octopus", "okapi", "opossum", "oryx", "ostrich",
        "otter", "owl", "ox", "oyster", "panther", "parrot", "partridge", "peafowl", "pelican", "penguin",
        "pheasant", "pig", "pigeon", "polar bear", "pony", "porcupine", "porpoise", "prairie dog", "quail",
        "quelea", "quetzal", "rabbit", "raccoon", "rail", "ram", "rat", "raven", "red deer", "red panda",
        "reindeer", "rhinoceros", "rook", "salamander", "salmon", "sand dollar", "sandpiper", "sardine",
        "scorpion", "sea lion", "sea urchin", "seahorse", "seal", "shark", "sheep", "shrew", "skunk",
        "snail", "snake", "sparrow", "spider", "spoonbill", "squid", "squirrel", "starling", "stingray",
        "stinkbug", "stork", "swallow", "swan", "tapir", "tarsier", "termite", "tiger", "toad", "trout",
        "turkey", "turtle", "viper", "vulture", "wallaby", "walrus", "wasp", "water buffalo",
        "weasel", "whale", "wildcat", "wolf", "wolverine", "wombat", "woodcock", "woodpecker", "worm",
        "wren", "yak", "zebra",
    ],

    "plants": [
        "acacia", "agave", "alder", "aloe", "amaranth", "anemone", "apple tree", "ash tree", "aspen",
        "azalea", "bamboo", "banana tree", "basil", "bay laurel", "beech", "begonia", "birch", "bird of paradise",
        "black-eyed Susan", "bluebell", "bougainvillea", "boxwood", "bromeliad", "buttercup", "cactus",
        "calendula", "camellia", "carnation", "cedar", "chamomile", "cherry tree", "chives", "chrysanthemum",
        "clematis", "clover", "coconut palm", "coffee plant", "coral bells", "cornflower", "cottonwood",
        "crocus", "cypress", "daffodil", "dahlia", "daisy", "dandelion", "date palm", "dogwood", "edelweiss",
        "elm", "eucalyptus", "evening primrose", "fern", "fig tree", "fir", "flax", "forget-me-not", "forsythia",
        "foxglove", "frangipani", "fuchsia", "gardenia", "garlic", "geranium", "ginger", "ginkgo biloba",
        "gladiolus", "goldenrod", "grapevine", "grass", "hawthorn", "heather", "hellebore", "hemlock",
        "hibiscus", "holly", "honeysuckle", "hosta", "hydrangea", "iris", "ivy", "jasmine", "juniper",
        "kale", "kentucky bluegrass", "lantana", "lavender", "lemon tree", "lilac", "lily", "lily of the valley",
        "lime tree", "lobelia", "lotus", "magnolia", "maple", "marigold", "marjoram", "mint", "mistletoe",
        "morning glory", "moss", "narcissus", "nasturtium", "oak", "olive tree", "orange tree", "orchid",
        "oregano", "pansy", "papaya tree", "parsley", "passion flower", "peach tree", "pear tree", "peony",
        "peppermint", "petunia", "pine", "pineapple plant", "pink", "pistachio tree", "poinsettia", "poplar",
        "poppy", "primrose", "rhododendron", "rose", "rosemary", "rubber plant", "sage", "sassafras",
        "sequoia", "snapdragon", "sorghum", "spearmint", "spider plant", "spruce", "strawberry plant",
        "sunflower", "sweet pea", "sweetgum", "sycamore", "tarragon", "tea plant", "thistle", "thyme",
        "tiger lily", "tobacco plant", "tomato plant", "tulip", "violet", "walnut tree", "water lily",
        "weeping willow", "wheat", "wisteria", "yew", "yucca", "zinnia",
    ],

    "flowers": [
        "acacia", "ageratum", "allium", "alstroemeria", "amaranthus", "amaryllis", "anemone", "angelonia",
        "anthurium", "aster", "astilbe", "azalea", "baby's breath", "begonia", "bellflower", "bird of paradise",
        "black-eyed Susan", "bleeding heart", "bluebell", "bougainvillea", "buttercup", "calendula",
        "calla lily", "camellia", "canna", "carnation", "catmint", "celosia", "chamomile", "cherry blossom",
        "chrysanthemum", "clematis", "columbine", "coneflower", "coreopsis", "cornflower", "cosmos",
        "crocus", "cyclamen", "daffodil", "dahlia", "daisy", "dame's rocket", "delphinium", "dianthus",
        "dusty miller", "edelweiss", "fairy primrose", "flamingo flower", "flax", "forget-me-not", "forsythia",
        "foxglove", "freesia", "fuchsia", "gardenia", "geranium", "gerbera", "gladiolus", "globe amaranth",
        "globe thistle", "goldenrod", "gypsophila", "hawthorn", "heather", "hibiscus", "hollyhock",
        "honeysuckle", "hydrangea", "hyacinth", "ice plant", "impatiens", "iris", "ixora", "jacob's ladder",
        "jasmine", "joe-pye weed", "kalanchoe", "kangaroo paw", "lantana", "larkspur", "lavender",
        "lilac", "lily", "lily of the valley", "lisianthus", "lupine", "magnolia", "marigold", "mimosa",
        "morning glory", "narcissus", "nasturtium", "oleander", "orchid", "ornamental kale", "pansy",
        "passion flower", "peony", "periwinkle", "petunia", "phlox", "plumeria", "poppy", "primrose",
        "queen anne's lace", "ranunculus", "rhododendron", "rose", "rosemary", "rudbeckia", "sage",
        "salvia", "scabiosa", "snapdragon", "snowdrop", "statice", "stock", "sunflower", "sweet pea",
        "sweet william", "tansy", "thistle", "tiger lily", "tulip", "verbena", "veronica", "violet",
        "waxflower", "wisteria", "yarrow", "zinnia",
    ],

    "shelters": [
        "apartment", "bungalow", "cabin", "castle", "chalet", "chateau", "condominium", "cottage", "dome",
        "duplex", "farmhouse", "flat", "fort", "hacienda", "hut", "igloo", "lodge", "loft", "mansion",
        "mobile home", "palace", "penthouse", "ranch", "residence", "shack", "shed", "shelter", "skyscraper",
        "studio", "teepee", "tent", "terraced house", "townhouse", "villa", "yurt", "wigwam", "windmill",
        "barracks", "dormitory", "hostel", "hotel", "inn", "lighthouse", "pagoda", "quonset hut", "silo",
        "tipi", "treehouse", "warehouse", "boathouse", "lean-to", "pavilion", "hall", "cathedral", "mosque",
        "monastery", "barn", "observatory", "hovel", "longhouse", "stilt house", "earth sheltered",
        "sod house", "dogtrot house", "log cabin", "adobe house", "cliff dwelling", "caravan", "houseboat",
        "camper", "recreational vehicle", "beach hut", "summer house", "greenhouse", "gazebo", "outhouse",
        "pueblo", "schoolhouse", "firehouse", "jailhouse", "courthouse", "pumphouse", "grange hall",
    ],

    "vehicles": [
        "sedan", "coupe", "convertible", "hatchback", "station wagon", "SUV", "crossover", "pickup truck",
        "van", "minivan", "cargo van", "box truck", "motorcycle", "scooter", "moped", "bicycle",
        "mountain bike", "road bike", "BMX bike", "tricycle", "quad bike", "go-kart", "golf cart",
        "tractor", "forklift", "dump truck", "garbage truck", "fire engine", "ambulance", "police cruiser",
        "limousine", "RV", "camper van", "motorhome", "school bus", "shuttle bus", "coach", "trolley",
        "streetcar", "tram", "train", "light rail vehicle", "subway car", "tank", "armored car",
        "snowmobile", "snowcat", "hovercraft", "jet ski", "speedboat", "sailboat", "yacht", "fishing boat",
        "canoe", "kayak", "rowing boat", "gondola", "cruise ship", "freighter", "aircraft carrier",
        "fighter jet", "helicopter", "glider", "biplane", "airliner", "drone", "hot air balloon",
        "blimp", "space shuttle", "bobsled", "luge", "skateboard", "roller skates", "inline skates",
        "wheelchair", "handcycle", "rickshaw", "horse carriage", "bullock cart", "dog sled",
    ],
}