word_lists = {
    "fruits": [
        "apple", "apricot", "avocado", "banana", "blackberry", "blueberry", "boysenberry", "breadfruit",
        "cantaloupe", "carambola", "cherimoya", "cherry", "cloudberry", "coconut", "cranberry", "date",
        "dragonfruit", "durian", "elderberry", "feijoa", "fig", "goji berry", "gooseberry", "grape",
        "grapefruit", "guava", "honeydew", "huckleberry", "jabuticaba", "jackfruit", "jambul", "jujube",
        "kiwi", "kumquat", "lemon", "lime", "longan", "loquat", "lychee", "mango", "mangosteen",
        "marionberry", "melon", "mulberry", "nectarine", "orange", "papaya", "passion fruit", "peach",
        "pear", "persimmon", "pineapple", "pitaya", "plantain", "plum", "pomegranate", "pomelo",
        "prickly pear", "quince", "raspberry", "red currant", "rambutan", "sapodilla", "sapote",
        "soursop", "star apple", "star fruit", "strawberry", "tamarillo", "tamarind", "tangerine",
        "ugli fruit", "watermelon", "white currant", "white sapote", "xigua", "yellow watermelon",
        "yuzu", "zucchini", "kaki",
    ],

    "animals": [
        "aardvark", "albatross", "alligator", "alpaca", "ant", "anteater", "antelope", "ape", "armadillo",
        "baboon", "badger", "barracuda", "bat", "bear", "beaver", "bee", "bison", "boar", "buffalo",
        "butterfly", "camel", "capybara", "caribou", "cassowary", "cat", "caterpillar", "cattle", "chamois",
        "cheetah", "chicken", "chimpanzee", "chinchilla", "clam", "cobra", "cockroach", "cod", "cormorant",
        "coyote", "crab", "crane", "crocodile", "crow", "curlew", "deer", "dinosaur", "dog", "dogfish",
        "dolphin", "donkey", "dove", "dragonfly", "duck", "dugong", "eagle", "echidna", "eel", "eland",
        "elephant", "elephant seal", "elk", "emu", "falcon", "ferret", "finch", "fish", "flamingo", "fly",
        "fox", "frog", "gaur", "gazelle", "gerbil", "giant panda", "giraffe", "gnat", "gnu", "goat",
        "goose", "goldfish", "gorilla", "goshawk", "grasshopper", "grouse", "guanaco", "gull", "hamster",
        "hare", "hawk", "hedgehog", "heron", "herring", "hippopotamus", "hornet", "horse", "human",
        "hummingbird", "hyena", "ibex", "ibis", "jackal", "jaguar", "jellyfish", "kangaroo", "kingfisher",
        "koala", "komodo dragon", "kookaburra", "kouprey", "kudu", "lapwing", "lark", "lemur", "leopard",
        "lion", "llama", "lobster", "locust", "loris", "louse", "lyrebird", "magpie", "mallard", "manatee",
        "mandrill", "mantis", "marten", "meerkat", "mink", "mole", "mongoose", "monkey", "moose", "mosquito",
        "mouse", "mule", "narwhal", "newt", "nightingale", "octopus", "okapi", "opossum", "oryx", "ostrich",
        "otter", "owl", "ox", "oyster", "panther", "parrot", "partridge", "peafowl", "pelican", "penguin",
        "pheasant", "pig", "pigeon", "polar bear", "pony", "porcupine", "porpoise", "prairie dog", "quail",
        "quelea", "quetzal", "rabbit", "raccoon", "rail", "ram", "rat", "raven", "red deer", "red panda",
        "reindeer", "rhinoceros", "rook", "salamander", "salmon", "sand dollar", "sandpiper", "sardine",
        "scorpion", "sea lion", "sea urchin", "seahorse", "seal", "shark", "sheep", "shrew", "skunk",
        "snail", "snake", "sparrow", "spider", "spoonbill", "squid", "squirrel", "starling", "stingray",
        "stinkbug", "stork", "swallow", "swan", "tapir", "tarsier", "termite", "tiger", "toad", "trout",
        "turkey", "turtle", "vicuña", "viper", "vulture", "wallaby", "walrus", "wasp", "water buffalo",
        "weasel", "whale", "wildcat", "wolf", "wolverine", "wombat", "woodcock", "woodpecker", "worm",
        "wren", "yak", "zebra",
    ],
}